### ISSUE TITLE
BadAuthentication using an App Password

### ISSUE THREAD

**Issue by keldrox** [YuriCosta/WhatsApp-GD-Extractor-Multithread#22]
Hi! I'm trying to test the script but I'm getting BadAuthentication

> {'Error': 'BadAuthentication'}

I've double checked the app password is ok, generated a second one just in case but same result. Not sure if it's a bug or a config issue.

Thank!

**Comment by mtrpires** [comment]
+1 to this -- I'm also getting BadAuthentication error, even though settings/requirements seem to be ok. Maybe something changed in the authentication method with Google?

**Comment by keldrox** [comment]
tested on linux, now it works, thanks!
