### ISSUE TITLE
GSuite account failure

### ISSUE THREAD

**Issue by B16f00t** [YuriCosta/WhatsApp-GD-Extractor-Multithread#28]
When you enter an .edu account linked to Gsuite,
Displays: 'Error': 'NeedsBrowser

**Comment by Alcazer** [comment]
**Troubleshooting**
If you have Error:Need Browser, go to this url to solve the issue: https://accounts.google.com/b/0/DisplayUnlockCaptcha

**Comment by Alcazer** [comment]
@B16f00t is it resolved?
