### ISSUE TITLE
BadAuthentication

### ISSUE THREAD

**Issue by Lars-** [YuriCosta/WhatsApp-GD-Extractor-Multithread#31]
I'm very sure that I'm using the right app password and email address and I tried 3 device_ids (2 from device id apps and one from adb).

How to troubleshoot this?

**Comment by Alcazer** [comment]
If everything is true, please backup google drive again and try latest version?

**Comment by trideeindhoven** [comment]
I am also running into the Bad Authentication error. Who knows what to do?
