### ISSUE TITLE
needs browser

### ISSUE THREAD

**Issue by ZioTano** [YuriCosta/WhatsApp-GD-Extractor-Multithread#36]
when i ask for list a message appears:
{'Error': 'NeedsBrowser', 'Url': 'https://accounts.google.com/signin/continue?sarp=1&scc=1&continue=https://accounts.google.com/o/android/auth?hl%3Den_us%26xoauth_display_name%3DAndroid%2BLogin%2BService%26source%3DAndroid%2BLogin&plt=AKgnsbu1nca04Czi-dLCxXYoUdZV99y_Wx2mOcX1UIy-u6FiVX-H1p4zWEir_dij03wieYNbQHmMrT7kLIJcz7uUqBrueK4bfbu3pDYE6LkcoMtuclcB9a4VXE8eaCP3xZ1MgQ938SXk', 'ErrorDetail': 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.'}

Even if i log in through aforementioned link browser stuck on "one moment please..."
![image](https://user-images.githubusercontent.com/6409081/143774414-56a58121-6d67-486b-838e-ccda1c29b32a.png)

**Comment by luanroyal** [comment]
you need to enable the account first at the link below
https://accounts.google.com/b/0/DisplayUnlockCaptcha

**Comment by ZioTano** [comment]
Unfortunately even with this link I receive the same error.
I think that recent google F2A authentication policy doesn't allow this kind of login anymore.
May you confirm?
Have you alternative solutions?
Thank you.

**Comment by lukaszmn** [comment]
You can create an app password in Google - it worked for me: https://myaccount.google.com/apppasswords
