### ISSUE TITLE
Requesting Google access... Failed

### ISSUE THREAD

**Issue by rodrigopar99** [YuriCosta/WhatsApp-GD-Extractor-Multithread#42]
Google can't retrieve 'token' in order for the script to work. My account doesn't have 2FA and I have already done the DisplayUnlockCaptcha process but nothing.

**Comment by nicolaslazo** [comment]
Hi, were you able to get it working?

**Comment by lukaszmn** [comment]
You can create an app password in Google - it worked for me: https://myaccount.google.com/apppasswords

**Comment by rodrigopar99** [comment]
> Hi, were you able to get it working?

Yes, it had to update gpsoauth module.
