### ISSUE TITLE
Displayunlockcaptcha didnt work anymore

### ISSUE THREAD

**Issue by vanders27** [YuriCosta/WhatsApp-GD-Extractor-Multithread#43]
So this is the first time displayunlockcaptcha didnt work for me, it always work like past 1 year but this didnt work anymore. is there any new update? Or maybe another solution

**Comment by luanroyal** [comment]
me too

**Comment by Bubblebug17** [comment]
Same with me ....

**Comment by YuriCosta** [comment]
Copy and paste the link the error gives to you. You'll be asked to login with the account you're trying to recover the backup from.
README will be updated soon.

**Comment by luanroyal** [comment]
> Copy and paste the link the error gives to you. You'll be asked to login with the account you're trying to recover the backup from. README will be updated soon.

are you brazilian?

**Comment by YuriCosta** [comment]
> > Copy and paste the link the error gives to you. You'll be asked to login with the account you're trying to recover the backup from. README will be updated soon.
> 
> are you brazilian?

Yes.


I took a look today and apparently google did something to bork the spoofed app oauth flow. I have no quick fix anytime soon.
I may look in the weekend how to fix it but don't hold your breaths :(
Google is requesting to login in the browser but after that, not even the DisplayUnlockCaptcha trick won't work anymore.
I looked up the responses from the browser login but I can't find any `Token` header response, only new `oauth_token` That I don't know yet how to implement.

Project is blocked until someone figures it out.

**Comment by luanroyal** [comment]
> Yes.
> 
> I took a look today and apparently google did something to bork the spoofed app oauth flow. I have no quick fix anytime soon. I may look in the weekend how to fix it but don't hold your breaths :( Google is requesting to login in the browser but after that, not even the DisplayUnlockCaptcha trick won't work anymore. I looked up the responses from the browser login but I can't find any `Token` header response, only new `oauth_token` That I don't know yet how to implement.
> 
> Project is blocked until someone figures it out.


Pois é, revirei toda a parte de configurações das contas e nao achei nada tambem, creio que tem 1 mês já isso, pois uso acesso pessoal em algumas contas gmail para acesso.

Thanks bro!

**Comment by petermcneil** [comment]
This version of gpsoauth just got released and seems to have fixed the oauth issue for me - https://github.com/simon-weber/gpsoauth/releases/tag/1.0.1
